# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mgr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
