# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_mgr', '0003_auto_20160629_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='admin_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins_of', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='member_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members_of', to='auth.Group'),
        ),
    ]
